language: python

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments
      - nodejs
      - npm
      - snapd

install:
    - sudo snap install hugo
    - rm -rf public || exit 0

script:
    - /snap/bin/hugo
    - npm install
    - node ./generatepdf.js

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
