language: python

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - apt-get install -y nodejs npm
    - rm -rf public || exit 0

script:
    - hugo
    - npm install
    - node ./generatepdf.js

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
